### ISSUE TITLE
Webserver setup instructions

### ISSUE THREAD

**Issue by heidihoward** [consensus-oracle/coracle#58]
I've tried this on OSX using:

```
brew install npm
cd coracle/web
node ./bin/www
```

But it fails with the following:

```
module.js:338
    throw err;
          ^
Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/heidi/coracle-local/web/app.js:1:77)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

**Comment by heidihoward** [comment]
I was missing the dependancies

```
npm install express serve-favicon morgan cookie-parser node-uuid debug jade serve-index moment
```

Is there a faster way to get the dependancies installed using the package.json file?
